const cors = require('cors')({ origin: true });

module.exports = (app, db) => {
  app.post('/api/v1/club', (req, res) => {
    cors(req, res, () => {
      try {
        const {
          name,
          about,
          topDrinks,
          address,
          webSite,
          phoneNo,
          hoursOfOperation,
        } = req.body;

        const data = {
          name,
          about,
          topDrinks,
          address,
          webSite,
          phoneNo,
          hoursOfOperation,
        };

        const clubRef = db.ref('clubs');

        // Generate a reference to a new location and add some data using push()
        const newClub = clubRef.push({
          club_name: name,
          club_about: about,
          top_drinks: topDrinks,
          club_address: address,
          club_website: webSite,
          club_phoneNo: phoneNo,
          club_hours: hoursOfOperation,
        });

        // Get the unique key generated by push()
        const postId = newClub.key;

        return res.status(200).json({
          id: postId,
          data: data,
        });
      } catch (err) {
        console.log({ err });
        return res.status(500).send(err);
      }
    });
  });
};
